# Book settings
title: Laboratorio 1
author: Mauro Silberberg
copyright: "2021"
logo: logo.png

only_build_toc_files: true

repository:
  url: https://github.com/maurosilber/labo1
  path_to_book: _sources
  branch: gh-pages

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  notebook_interface: "classic"
