name: publish-book

# Only run this when the master branch changes
on:
  push:
    branches: [ main ]

jobs:
  # This job installs dependencies, build the book, and pushes it to `gh-pages`
  publish-book:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build the book
      run: jupyter-book build .

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
